import type { Metadata } from "next";
import { Background } from "@/components/ui/background";
import { SiteHeader } from "@/components/site-header";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark h-full antialiased">
      <body className="min-h-full flex flex-col">
        <Background variant="image">
          <SiteHeader />
          {children}
        </Background>
      </body>
    </html>
  );
}
